{
 "title": "ksqlDB",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "label": "environment", "query": "label_values(env)" },
   { "name": "cluster", "query": "label_values(ksql_cluster)" },
   {
    "name": "instance",
    "query": "label_values(ksql_ksql_engine_query_stats_liveness_indicator,instance)"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running Queries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(ksql_ksql_engine_query_stats_running_queries{env=\"$env\",instance=~\"$instance\",ksql_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Not Running Queries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(ksql_ksql_engine_query_stats_not_running_queries{env=\"$env\",instance=~\"$instance\",ksql_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Active Queries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(ksql_ksql_engine_query_stats_num_active_queries{env=\"$env\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Persistent Queries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(ksql_ksql_engine_query_stats_num_persistent_queries{env=\"$env\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Rebalancing Queries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(ksql_ksql_engine_query_stats_rebalancing_queries{env=\"$env\",instance=~\"$instance\",ksql_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Error Queries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(ksql_ksql_engine_query_stats_error_queries{env=\"$env\",instance=~\"$instance\",ksql_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Rate Messages Consumers",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ksql_consumer_metrics_consumer_messages_per_sec{env=~\"$env\",instance=~\"$instance\"}",
     "legendFormat": "topic: {{key}} - group.id: {{id}}"
    }
   ]
  },
  {
   "title": "Messages Produced Per Sec",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ksql_producer_metrics_messages_per_sec{env=~\"$env\",instance=~\"$instance\"}",
     "legendFormat": "topic: {{key}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"ksql\",env=\"$env\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{cluster}}-{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"ksql\",env=\"$env\",instance=~\"$instance\"})",
     "legendFormat": "{{cluster}}-{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Garbage Collection",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "percentunit", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"ksql\",env=\"$env\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{cluster}}-{{instance}}"
    }
   ]
  }
 ]
}