version: "2.3"
services:
  zookeeper1:
    volumes:
      - $MONITORING_STACK/../shared-assets/jmx-exporter/:/usr/share/jmx-exporter
    environment:
      EXTRA_ARGS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.12.0.jar=7001:/usr/share/jmx-exporter/zookeeper.yml

  zookeeper2:
    volumes:
      - $MONITORING_STACK/../shared-assets/jmx-exporter/:/usr/share/jmx-exporter
    environment:
      EXTRA_ARGS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.12.0.jar=7009:/usr/share/jmx-exporter/zookeeper.yml

  zookeeper3:
    volumes:
      - $MONITORING_STACK/../shared-assets/jmx-exporter/:/usr/share/jmx-exporter
    environment:
      EXTRA_ARGS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.12.0.jar=7010:/usr/share/jmx-exporter/zookeeper.yml

  kafka1:
    volumes:
      - $MONITORING_STACK/../shared-assets/jmx-exporter/:/usr/share/jmx-exporter
    environment:
      EXTRA_ARGS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.12.0.jar=7002:/usr/share/jmx-exporter/kafka_broker.yml

  kafka2:
    volumes:
      - $MONITORING_STACK/../shared-assets/jmx-exporter/:/usr/share/jmx-exporter
    environment:
      EXTRA_ARGS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.12.0.jar=7003:/usr/share/jmx-exporter/kafka_broker.yml

  streams-demo:
    volumes:
      - $MONITORING_STACK/../shared-assets/jmx-exporter/:/usr/share/jmx-exporter
    environment:
      JAVA_OPTS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.12.0.jar=7004:/usr/share/jmx-exporter/kafka_streams.yml

  connect:
    volumes:
      - $MONITORING_STACK/../shared-assets/jmx-exporter/:/usr/share/jmx-exporter
    environment:
      EXTRA_ARGS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.12.0.jar=7005:/usr/share/jmx-exporter/kafka_connect.yml

  schemaregistry:
    volumes:
      - $MONITORING_STACK/../shared-assets/jmx-exporter/:/usr/share/jmx-exporter
    environment:
      EXTRA_ARGS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.12.0.jar=7006:/usr/share/jmx-exporter/confluent_schemaregistry.yml

  ksqldb-server:
    volumes:
      - $MONITORING_STACK/../shared-assets/jmx-exporter/:/usr/share/jmx-exporter
    environment:
      KSQL_OPTS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.12.0.jar=7007:/usr/share/jmx-exporter/confluent_ksql.yml

  restproxy:
    volumes:
      - $MONITORING_STACK/../shared-assets/jmx-exporter/:/usr/share/jmx-exporter
    environment:
      KAFKAREST_OPTS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.12.0.jar=7008:/usr/share/jmx-exporter/confluent_rest.yml

  prometheus:
    image: prom/prometheus:v2.11.1
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - $MONITORING_STACK/assets/prometheus/prometheus-config/:/etc/prometheus/

  node-exporter:
    image: prom/node-exporter:v0.18.1
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points"
      - "^(aufs|proc|nsfs|shm|cgroup|tmpfs|binfmt_misc|debugfs|devpts|fusectl|hugetlbfs|fuse.lxcfs|mqueue|pstore|securityfs|sysfs|autofs|devtmpfs|configfs)"

